version: '3.8'

services:
  transformerlab:
    build: .
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "8338:8338"
    volumes:
      - ~/.transformerlab:/root/.transformerlab
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
